name: kgrs
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.2
  - python=3.11.13
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - colorama==0.4.6
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - idna==3.4
      - jinja2==3.1.6
      - joblib==1.5.2
      - lightning-utilities==0.15.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.5
      - numpy==1.26.4
      - packaging==25.0
      - pillow==11.3.0
      - propcache==0.4.1
      - pytorch-lightning==2.1.0
      - pyyaml==6.0.3
      - requests==2.28.1
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timeout-decorator==0.5.0
      - torch==2.0.0+cpu
      - torchaudio==2.0.0+cpu
      - torchmetrics==1.8.2
      - torchvision==0.15.0+cpu
      - tqdm==4.66.1
      - typing-extensions==4.15.0
      - urllib3==1.26.13
      - yarl==1.22.0
prefix: C:\Users\lenovo\anaconda3\envs\kgrs
